### ISSUE TITLE
Potential performance regression

### ISSUE THREAD

**Issue by diizzyy** [sdroege/ebur128#52] opened 2023-04-11 08:39 UTC
During my tests it seems like ebur128 is about 20% slower than [libebur128](libebur128) when used in [rsgain](https://github.com/complexlogic/rsgain) which doesn't seem to be expected performance.

Hardware:
Intel 11th Gen (Tigerlake)

Software:
FreeBSD 13.2-RELEASE (amd64)

ebur128 0.1.7 (compiled using Rust 1.68.2) and commits e652c0d + 1b1541c
Relevant compiler flags: ```-C opt-level=2 -C panic=abort -C codegen-units=1 -C target-cpu=tigerlake```

libebur128 1.2.6 (compiled using LLVM/clang 14.0.5)
Relevant compiler flags (no lto): ```-O2 -march=tigerlake```

rsgain 3.2.1 (used for testing)

For testing I used a ~8h long AAC file in m4a

Command used for testing:  ```rsgain easy /path/to/directory```

**Comment by sdroege** [comment] 2023-04-12 08:33
I shortly checked this here and I can confirm that in my test it's 35% slower even (before someone asks, LTO or -O3 on the Rust side makes no real difference).

I'll take a closer look at what's going on there and if it's a regression or simply somehow a case I didn't measure before.

**Comment by diizzyy** [comment] 2023-04-12 08:54
Sounds great, thanks for confirming

**Comment by diizzyy** [comment] 2023-04-27 06:33
Hi,

Just curious, did you find the cause?

Best regards,
Daniel

**Comment by sdroege** [comment] 2023-04-27 06:44
Not yet, I had no time to look in detail yet. Too many work-related obligations. If you want to help, my first step would be to check whether the first release without any C implementation had the same behaviour or was faster.

  * If it had the same behaviour then this is a case I didn't look into before for some reason and needs more analysis why it's slower. I'd also check that version with the Rust stable version from when it was released as it could also be a performance regression in the Rust compiler or LLVM toolchain.
  * If that version was faster than `git bisect` should be able to easily find the commit that made it slower.

The difference between the Rust and C version is most likely going to be in the filter according to a flamegraph I created from your testcase. The filter is taking almost all the time. Specifically `process()` and `calc_gating_block()`.

**Comment by sdroege** [comment] 2023-04-27 07:44
Shortly did the first part here between other things. 0.1.2 takes 17s, the C implementation takes 19s and current git main takes 27s. So there's clearly a regression somewhere between 0.1.2 and git main.

**Comment by sdroege** [comment] 2023-04-27 07:58
c28b8b95379d00673183464e11efb657a847cebe is the culprit. Reverting that with git main gives 16s for my test.

I'll make another release without that commit some time later or tomorrow, but this needs some investigation why it doesn't compile down to the exact same code.

**Comment by diizzyy** [comment] 2023-04-27 08:52
That's great news, thanks for the quick fix!

**Comment by sdroege** [comment] 2023-04-27 11:05
There's a difference in the assembly but I'm not sure I get why that makes such a big difference in speed.

### Fast version

```asm
		// /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ptr/mut_ptr.rs : 479
		unsafe { intrinsics::offset(self, count) as *mut T }
	lea rdx, [rdx + 8*r8]

		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 222
		- a[1] * filter_state[1]
	movsd xmm2, qword ptr [rbx + 8*rcx + 8]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 223
		- a[2] * filter_state[2]
	movupd xmm1, xmmword ptr [rbx + 8*rcx + 16]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 225
		- a[4] * filter_state[4];
	movsd xmm3, qword ptr [rbx + 8*rcx + 32]

	mov rbx, r10
	mov rcx, r12
	xor r8d, r8d

	.p2align	4, 0x90
.LBB130_72:
		// /home/slomo/Projects/rust/ebur128/src/utils.rs : 111
		func(&v[channel], u)
	movsx r14d, word ptr [rbx]

		// /home/slomo/.cargo/registry/src/github.com-1ecc6299db9ec823/dasp_sample-0.11.0/src/conv.rs : 233
		s as f64 / 32_768.0
	xorps xmm4, xmm4
	cvtsi2sd xmm4, r14d
	mulsd xmm4, xmm0
	movsd xmm5, qword ptr [rdi + 1840]

		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 222
		- a[1] * filter_state[1]
	mulsd xmm5, xmm2
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 221
		filter_state[0] = (*src).to_sample::<f64>()
	subsd xmm4, xmm5
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 223
		- a[2] * filter_state[2]
	movupd xmm5, xmmword ptr [rdi + 1848]
	mulpd xmm5, xmm1
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 221
		filter_state[0] = (*src).to_sample::<f64>()
	subsd xmm4, xmm5
	unpckhpd xmm5, xmm5
	subsd xmm4, xmm5
	movsd xmm5, qword ptr [rdi + 1864]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 225
		- a[4] * filter_state[4];
	mulsd xmm5, xmm3
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 221
		filter_state[0] = (*src).to_sample::<f64>()
	subsd xmm4, xmm5
	movsd qword ptr [rsi], xmm4
	movsd xmm5, qword ptr [rdi + 1792]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 226
		*dest = b[0] * filter_state[0]
	mulsd xmm5, xmm4
	movsd xmm6, qword ptr [rdi + 1800]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 227
		+ b[1] * filter_state[1]
	mulsd xmm6, xmm2
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 226
		*dest = b[0] * filter_state[0]
	addsd xmm6, xmm5
	movsd xmm5, qword ptr [rdi + 1808]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 228
		+ b[2] * filter_state[2]
	mulsd xmm5, xmm1
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 226
		*dest = b[0] * filter_state[0]
	addsd xmm5, xmm6
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 229
		+ b[3] * filter_state[3]
	movapd xmm6, xmm1
	unpckhpd xmm6, xmm1
	movapd xmm7, xmm6
	mulsd xmm7, qword ptr [rdi + 1816]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 230
		+ b[4] * filter_state[4];
	mulsd xmm3, qword ptr [rdi + 1824]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 226
		*dest = b[0] * filter_state[0]
	addsd xmm7, xmm5
	addsd xmm3, xmm7
	movsd qword ptr [rdx + 8*r8], xmm3

		// /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/iter/adapters/zip.rs : 274
		self.index += 1;
	inc r8

		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 232
		filter_state[4] = filter_state[3];
	movhpd qword ptr [rsi + 32], xmm1
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 233
		filter_state[3] = filter_state[2];
	movlpd qword ptr [rsi + 24], xmm1
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 234
		filter_state[2] = filter_state[1];
	movsd qword ptr [rsi + 16], xmm2
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 235
		filter_state[1] = filter_state[0];
	movsd qword ptr [rsi + 8], xmm4

		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 223
		- a[2] * filter_state[2]
	unpcklpd xmm2, xmm1
```

### Slow version

```asm
		// /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ptr/mut_ptr.rs : 479
		unsafe { intrinsics::offset(self, count) as *mut T }
	lea rdx, [rdx + 8*rcx]

	mov rbx, r15
	mov rcx, r11
	xor r8d, r8d

	.p2align	4, 0x90
.LBB130_72:
		// /home/slomo/Projects/rust/ebur128/src/utils.rs : 111
		func(&v[channel], u)
	movsx r14d, word ptr [rbx]

		// /home/slomo/.cargo/registry/src/github.com-1ecc6299db9ec823/dasp_sample-0.11.0/src/conv.rs : 233
		s as f64 / 32_768.0
	xorps xmm1, xmm1
	cvtsi2sd xmm1, r14d

		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 222
		- a[1] * filter_state[1]
	movsd xmm2, qword ptr [rsi + 8]

		// /home/slomo/.cargo/registry/src/github.com-1ecc6299db9ec823/dasp_sample-0.11.0/src/conv.rs : 233
		s as f64 / 32_768.0
	mulsd xmm1, xmm0
	movsd xmm3, qword ptr [rdi + 1840]

		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 222
		- a[1] * filter_state[1]
	mulsd xmm3, xmm2
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 223
		- a[2] * filter_state[2]
	movsd xmm4, qword ptr [rsi + 16]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 221
		filter_state[0] = (*src).to_sample::<f64>()
	subsd xmm1, xmm3
	movsd xmm3, qword ptr [rdi + 1848]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 223
		- a[2] * filter_state[2]
	mulsd xmm3, xmm4
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 224
		- a[3] * filter_state[3]
	movsd xmm5, qword ptr [rsi + 24]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 221
		filter_state[0] = (*src).to_sample::<f64>()
	subsd xmm1, xmm3
	movsd xmm3, qword ptr [rdi + 1856]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 224
		- a[3] * filter_state[3]
	mulsd xmm3, xmm5
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 225
		- a[4] * filter_state[4];
	movsd xmm6, qword ptr [rsi + 32]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 221
		filter_state[0] = (*src).to_sample::<f64>()
	subsd xmm1, xmm3
	movsd xmm3, qword ptr [rdi + 1864]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 225
		- a[4] * filter_state[4];
	mulsd xmm3, xmm6
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 221
		filter_state[0] = (*src).to_sample::<f64>()
	subsd xmm1, xmm3
	movsd qword ptr [rsi], xmm1
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 226
		*dest = b[0] * filter_state[0]
	mulsd xmm1, qword ptr [rdi + 1792]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 227
		+ b[1] * filter_state[1]
	mulsd xmm2, qword ptr [rdi + 1800]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 228
		+ b[2] * filter_state[2]
	mulsd xmm4, qword ptr [rdi + 1808]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 226
		*dest = b[0] * filter_state[0]
	addsd xmm2, xmm1
	addsd xmm4, xmm2
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 229
		+ b[3] * filter_state[3]
	mulsd xmm5, qword ptr [rdi + 1816]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 226
		*dest = b[0] * filter_state[0]
	addsd xmm5, xmm4
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 230
		+ b[4] * filter_state[4];
	mulsd xmm6, qword ptr [rdi + 1824]
		// /home/slomo/Projects/rust/ebur128/src/filter.rs : 226
		*dest = b[0] * filter_state[0]
	addsd xmm6, xmm5
	movsd qword ptr [rdx + 8*r8], xmm6

		// /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/iter/adapters/zip.rs : 274
		self.index += 1;
	inc r8

		// /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/intrinsics.rs : 2460
		copy(src, dst, count)
	movupd xmm1, xmmword ptr [rsi]
	movupd xmm2, xmmword ptr [rsi + 16]
	movupd xmmword ptr [rsi + 24], xmm2
	movupd xmmword ptr [rsi + 8], xmm1
```

There's quite a bit of noise in the upper part, with the faster one doing additional unpacks (so it should be slower?). The interesting part is *probably* that the slower version uses unaligned moves for shifting the filter state (`movupd`) while the fast version uses aligned ones (`movsd`). Also in the slow case it always copies between memory and registers (also in the middle of the calculation), while in the fast case it keeps the filter state in register all the time and just updates the memory.

There seems to be a bit of information lost to the compiler along the way and it can then optimize the whole thing not as good. Not sure this is worth a rustc or LLVM issue, seems very annoying.

I'll just revert it for now.

**Closed as completed** 2023-04-27 11:07 UTC
